/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { Lock } from "./Lock";
export type { Staking } from "./Staking";
