/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenSol from "./Token.sol";
export { Lock__factory } from "./Lock__factory";
export { Staking__factory } from "./Staking__factory";
